### ISSUE TITLE
Why are seeds regenerated every time?

### ISSUE THREAD

**Issue by Jimmy-Z** [dpbriggs/growable-bloom-filters#2]
https://github.com/dpbriggs/growable-bloom-filters/blob/master/src/lib.rs#L64

Why not simply store k1~k4 in self in new?

**Comment by dpbriggs** [comment]
Hey, thanks for catching that! Definitely an oversight. I've pushed `1.0.3` (a596552) which stores k1~k4 inline.

**Comment by dpbriggs** [comment]
I think I'll close this issue as fixed. If you notice anything else, please feel free to make another issue or a pull request. Thanks for taking an interest!
