### ISSUE TITLE
save and load

### ISSUE THREAD

**Issue by Noname400** [dpbriggs/growable-bloom-filters#5]
how to save the created filter to a file for reuse?
and how to download it later?

**Comment by dpbriggs** [comment]
Hey! Thanks for taking an interest.

As shown in the first example in the README you can use `serde_json` to serialize the filter to a file. Here's [an example of deserialization in the serde the documentation](https://docs.serde.rs/serde_json/de/fn.from_reader.html#example). And here's [a serialization function](https://docs.serde.rs/serde_json/ser/fn.to_writer.html) you could use (pass a `&mut File`).

To download it you'll presumably upload it somewhere (google drive? a server?).

**Comment by dpbriggs** [comment]
I think you have enough to figure this out. I'll be closing this issue
