### ISSUE TITLE
Tunable growth factor and tightening ratio

### ISSUE THREAD

**Issue by whitfin** [dpbriggs/growable-bloom-filters#7]
The comments above the code [here](https://github.com/dpbriggs/growable-bloom-filters/blob/master/src/lib.rs#L248-L249) seem to imply they were meant as defaults, but there's no way to provide them for custom values. Was this just something that fell behind, or was it intentionally left out? If the latter, would a contribution be accepted? 

I'm trying to migrate to this library, but the library I'm using had hardcoded values of `2` and `0.5`, whereas this library is hardcoded to `2` and `0.85`. I'd like to move over as this implementation is faster, but not being able to tune the values to match means I have to bump major (as the results are obviously changing).

**Comment by dpbriggs** [comment]
Interesting - I suppose we could just allow users to specify those values. I wonder if a builder API is overkill? I'll try that out and see how it feels.

**Comment by dpbriggs** [comment]
Alrighty, 2.1.0 is published! It offers a builder that allows to specify those values. Let me know if that works for you :^)

**Comment by whitfin** [comment]
@dpbriggs awesome, this works exactly as I hoped :) thank you for getting to it so quickly!
